=head1 berrybrew

The perlbrew for Windows Strawberry Perl! berrybrew can download, install and manage multiple versions of Strawberry Perl for Windows.

=head2 Warning

This tool is in beta, has been tested on Windows 7 and 8 64bit machines, with .Net framework 4.5 only.

=head2 Synopsis

    > berrybrew available

    The following Strawberry Perls are available:

            5.20.1_64 [installed]
            5.20.1_32 [installed]
            5.18.4_64
            5.18.4_32
            5.16.3_64
            5.16.3_32
            5.14.4_64
            5.14.4_32
            5.12.3_32
            5.10.1_32
    
    > berrybrew install 5.10.1_32
    
    > berrybrew switch 5.10.1_32
    

=head2 Installation

Use the precompiled binary:

    git clone https://github.com/sillymoose/berrybrew
    cd berrybrew/bin

Compile your own version with Mono:

    git clone https://github.com/sillymoose/berrybrew
    mcs src/berrybrew.cs -lib:lib -r:ICSharpCode.SharpZipLib.dll -out:bin/berrybrew.exe
    cd bin

=head2 Commands

    berrybrew <command> [option]

    available   List available Strawberry Perl versions and which are installed
    install     Download, extract and install a Strawberry Perl
    switch      Switch to use a different Strawberry Perl

=head2 Requirements

=over

=item *

.Net Framework 2.0 or higher

=item *

Windows only! (Tested on Windows 7 64 bit)
    
=item *

L<Mono|http://www.mono-project.com/> (only if compiling your own version)
 
=back

=head2 To Do

=over

=item *

Add new commands: uninstall, exec

=item *

Test on Windows XP and Windows 8

=item *

Add Test Suite

=back

=head2 Version

0.01

=head2 License

2 Clause FreeBSD - see LICENSE

=head2 Author

David Farrell L<http://perltricks.com>

=head2 See Also

=over 

=item *

L<StrawberryPerl.com|http://strawberryperl.com> - Strawberry Perl for Windows

=item *

L<Perlbrew|http://perlbrew.pl> - the original Perl version manager for Unix based systems

=back

=cut
